name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v6
        with:
          go-version: 1.25.x
      - uses: actions/setup-node@v6
        with:
          node-version: '20'
      - uses: actions/checkout@v5
      - run: make download-tools
      - run: make install
      - run: make generate
      - run: make build-js
        env:
          NODE_OPTIONS: --openssl-legacy-provider
      - run: make lint
      - run: make test
      - if: startsWith(github.ref, 'refs/tags/v')
        run: echo "$DOCKER_PASS" | docker login --username "traggoci" --password-stdin
        env:
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      - if: startsWith(github.ref, 'refs/tags/v')
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
